<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Sale</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>d2828b38-90fe-4ece-81dd-e66fc3d57a49</testSuiteGuid>
   <testCaseLink>
      <guid>24995bde-70da-4a53-be7d-40e421ed7d46</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/TC_Sales_001</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4cd89d7-44db-4f5e-b9a1-ea824144e869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19f3cd86-c171-4182-92de-1189c115e4e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e038ab76-1773-4c27-9bd4-b36e10c54626</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a338cfa9-97cc-4cb0-b2c2-691d009a8261</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>829762c5-6345-45d0-a2fc-defa850e9fe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc6e3761-74e5-4139-901b-ae2e259a7e45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d15a9da-02ff-4546-a91f-f78f3333c622</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/TC_Sales_005</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>05647078-50a0-4a23-96b2-dc413cd9c8c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/TC_Sales_006</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d95c7e-4cc1-4775-8dea-5d8281aaa40a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1b61761a-4ff2-4a12-8037-1be458b89f2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FirstView/Sale/TC_Sales_003</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8f7d4f8-98f2-4365-9515-ae355f040894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a3921ad-0125-421d-93ee-347d41db8e1b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
